### ISSUE TITLE
Light Theme on Mobile Revision

### ISSUE THREAD

**Issue by platschi** [Kwenta/kwenta#1214]
### Subject of the issue
Light theme has been implemented on desktop, and should work for the most part on mobile, too. There are several small issues on light theme when on responsive mobile view which should be dealt with, in order to officially release light theme support for mobile. This ticket lists known issues, however we should make sure mobile light theme on Kwenta matches the intended design (see comments below)
 
#### Navigation

- [x] Implement a light/dark theme switch into mobile navigation settings (#1219)
- [ ] Add "Menu" text label when hamburger menu is actively selected (Note: "Settings" label for wallet menu click is being added already in #1333)

- [ ] Fix link colors (active/inactive) to something more readable:

![Screen Shot 2022-08-30 at 10 36 14](https://user-images.githubusercontent.com/548702/187451391-5972ef9f-2db5-48a5-86c9-632fe72edf36.png)

- [ ] Fix sub-navigation button background colors

![Screen Shot 2022-08-30 at 10 36 39](https://user-images.githubusercontent.com/548702/187451503-10dc32e6-0fba-4d82-b8ac-409f040bdffc.png)

#### Dashboard

- [ ] Headers: Portfolio, Open Positions, Futures Markets yellow-ish is way too bright on mobile. Suggestion to change to: `text-shadow: rgb(242, 242, 242) 0px 1px 3px` when on light theme

![Screen Shot 2022-08-30 at 10 39 56](https://user-images.githubusercontent.com/548702/187452316-bf19d473-180e-49c7-9a3d-2bf704c31622.png)

#### Markets

- [ ] Dropdown menu: Fix PERP price color to be responsive to theme selection, same with change % text color (green/red colors for 24H Change in selected PERP are not aligned with other PERPs in dropdown, see screenshot:

![Screen Shot 2022-08-30 at 10 43 02](https://user-images.githubusercontent.com/548702/187452986-9c000030-b1b6-4573-8ddd-25b0b528449b.png)

- [ ] Headers: Fix text-shadow everywhere (same as dashboard): Account, Trade History, Stats, Orders, Trade, Transfers tab, Open Position etc.
- [ ] Suggestion: Update light theme labels (MarketDetails, MarginInfoBox, FeeBox etc. etc.) to use `#515151` rather than the less accessible `#787878`

#### Trades & Transfers tabs: 
- SHORT/LONG text colors should be updated, see Stats Skew for correct red/green colors on light theme
- On Transfers tab, text labels are unreadable/not updated to theme colors

![Screen Shot 2022-08-30 at 10 51 43](https://user-images.githubusercontent.com/548702/187455025-a2e95982-15b2-4840-956b-b53b4859de44.png)
![Screen Shot 2022-08-30 at 10 52 15](https://user-images.githubusercontent.com/548702/187455228-2fd1b0bf-eb45-4af4-a774-58a6674523d2.png)

#### Confirm Order Modal

- [ ] Whole modal on mobile still uses dark theme!

![Screen Shot 2022-08-30 at 10 50 35](https://user-images.githubusercontent.com/548702/187454680-b75c4a25-5116-4e82-9107-20e96d2bfbe4.png)

#### Exchange

- [ ] Headers: Fix text-shadow for "From" and "To"
- [ ] Update "Swap" button from gold button to new design
- [ ] For quick % selector, when value is selected background is using dark theme setting (see screenshot) 
- [ ] Consider updating labels from `#787878` to `#515151` for better readability (see above)

![Screen Shot 2022-08-30 at 10 56 15](https://user-images.githubusercontent.com/548702/187456115-69e82a84-6206-4161-b04c-d49ca8389e8f.png)

#### Bounty
350 $OP

**Comment by asherism** [comment]
synthswap/lightmode:
https://www.figma.com/file/YWU3PMsnqZaqr1gABgAFJK/UI-Refresh?node-id=5975%3A32311
<img width="320" alt="image" src="https://user-images.githubusercontent.com/11524787/193342694-eb42c551-e6bc-4caa-82cc-15691d07e511.png">

**Comment by asherism** [comment]
mobile futures/lightmode:
https://www.figma.com/file/YWU3PMsnqZaqr1gABgAFJK/UI-Refresh?node-id=2058%3A18651
<img width="1289" alt="image" src="https://user-images.githubusercontent.com/11524787/193342902-dd925848-15f7-46f4-8341-7a9de51a36b2.png">

**Comment by asherism** [comment]
mobile dashboard/lightmode:
https://www.figma.com/file/YWU3PMsnqZaqr1gABgAFJK/UI-Refresh?node-id=2562%3A27069
<img width="1397" alt="image" src="https://user-images.githubusercontent.com/11524787/193343310-99e55010-7775-4f9c-b2bf-020352218847.png">
