### ISSUE TITLE
Bedrock: Checklist

### ISSUE THREAD

**Issue by platschi** [Kwenta/kwenta#1868]
### Subject of the issue
Dev docs by Optimism at https://community.optimism.io/docs/developers/bedrock/#

### Checklist

- [ ] Verify subgraphs work as intended
- [ ] Verify block production time changes do not influence Kwenta functionality
- [ ] EIP-1559 support

Verify hardcoded gas estimates and other places where we estimate gas price and upgrade to EIP-1559 compatibility (Exchange, Order Confirm/Modify/Close Modals, Deposit/Withdraw, etc.)

- [ ] ETH Balances `OVM_ETH` contract will change, any implications for CM ETH deposits or Exchange?

- tbd
