### ISSUE TITLE
Perps V2 Outstanding Issues

### ISSUE THREAD

**Issue by Tburm** [Kwenta/kwenta#1878]
## Priority

- [ ] Leifu: #1974
- [x] Troy: Add responsive colors on price updates (#1832)
- [x] Adam: #1839 (PR: #1973)

## Refactor:

- [x] #1958

## Low priority
- [ ] Define PnL calculations and show PnL in Trade History
- [ ] #1935 
- [x] Improve markets dropdown for long list of markets

## Done
- [x] Enable offchain order execution (#1914)
- [x] Add button loading state for order execution/cancellation (#1914)
- [x] Fix trade panel "Deposit margin" display logic (#1919)
- [x] Remove hard-coded frontend fix for funding [link](https://github.com/Kwenta/kwenta/blob/e63cc50326f33553abcd03a7e73c72f3eb8c6caa/sections/futures/MarketDetails/useGetMarketData.ts#L52) (#1918)
- [x] #1904 
- [x] Update delayed order query to use multicall [link](https://github.com/Kwenta/kwenta/blob/4cd3fa77285ee6c2482f7772be1d4741a711cbdd/state/futures/actions.ts#L319) (#1925)
- [x] Update "oracle price" to "mark price" on dashboard (#1923)
- [x] Clean up order type naming (`delayed offchain` -> `delayedOffchain`) (#1922)
- [x] Update 1H Funding Rate tooltip text to explain new velocity-based model (#1939)
- [x] #1930 (#1940)
- [x] Reenable margin preview (#1931)
- [x] #1932 
- [x] Decide if we want to kick out (broken) Spot Markets table
- [x] Landing Page: ETH market data incorrect (100% price change, no volume shown) [fixed in #1926)
