### ISSUE TITLE
UI Refresh: Futures UI / UX tasks

### ISSUE THREAD

**Issue by avclarke** [Kwenta/kwenta#2113]
### Top Priority
- [x] Add market context to edit positions modals (Edit size, edit leverage, set SL / TP, close position).
       - Now modals can be opened from any market we need to show which market you are editing.
- [x] Improve stop loss / take profit UX for removing an existing order
- [x] Markets drop down re-positioning
- [x] Add UI to encourage users to move to smart margin (related to #2102)
- [x] New global trades history positioning
- [x] A way to show / hide global trade history 
- [x] Funding rate time period drop down options (Market details bar)
- [x] Hover states for buttons etc
- [x] Review mobile designs to settle on general structure
- [x] Review mobile designs to check it supports all desktop functionality
- [x] Improve delayed order pending feedback (https://github.com/Kwenta/kwenta/issues/2067)
- [x] Conditional Open orders table
  - [x] Add cancel all option
- [x] Update home page image 

**Isolated margin:**
- [x] Add an option to deposit within the new trade panel UI (when no balance)
- [x] ~~Add a step in order confirmation for possible depositing more margin before submitting (this will allow us to maintain consistent UI with smart margin)~~

**Smart Margin:**
- [x] Account onboarding flow - triggered when a user attempts to submit an order before they've created an account
    - [x] Add socket to onboard
- [x] Withdraw idle margin to wallet (Manage balance) - also display what markets idle margin lies in
- [x] Add reduce only option to trade panel
- [x] Edit stop loss / take profit modal

**Shared Modals**
- [x] Modify existing positions size / margin
- [x] Close position modal
- [x] Manage balance modal (Low priority can use existing withdraw for now)

**Shared items:**
- [x] Order history table
- [x] Trade history table
- [x] Transfers table
- [x] Expand balance view on trade panel (implemented without design currently)
- [x] Revised order confirmation view (The top overview section could be improved)
- [x] Add positions count to positions tab
- [x] Show available OI in trade panel so it's clear when inputting size
- [x] Mobile designs
- [x] Light theme designs
- [x] Improved liquidation feedback (https://github.com/Kwenta/kwenta/issues/2151)
