### ISSUE TITLE
UI Refresh: Implementation task list

### ISSUE THREAD

**Issue by avclarke** [Kwenta/kwenta#2119]
### Shared Futures Page Components

- [ ] Polish trade panel UI
   - [ ] Add balance component to trade panel
   - [ ] Add feedback for when delayed order is already pending
   - [ ] Remove slider toggle and move slider to permanently below leverage input
   - [ ] Update leverage option buttons
   - [ ] Add liquidation price below fees
   - [ ] Show available OI when inputting size
- [ ] Positions table
- [ ] Orders table
- [ ] Transfers table
- [ ] History table
- [ ] Markets drop down with favourites added
- [ ] Updated order confirmation views
- [ ] Update tabs styling and add count to positions tab

### Shared Modals

- [ ] Edit margin modal (partially done)
- [ ] Edit position size modal (Can update ClosePositionSizeInput to work for this) 
- [ ] Close position modal
- [ ] Manage balance modal

### Cross margin modals

- [ ] Stop loss and take profit modal
- [ ] Onboard / account creation flow - appears before order confirmation when a user doesn't have an account
