### ISSUE TITLE
OP Rewards: Implement Rewards page & badge

### ISSUE THREAD

**Issue by platschi** [Kwenta/kwenta#2153]
### Subject of the issue
Integrate a new rewards page where users can claim their Kwenta trading rewards, upcoming OP trading rewards as well as OP. trading rewards from Synthetix.

Integration can be done against the `cm-v2` branch as part of the global UI refresh and SM launch.

### Design
See Figma: https://www.figma.com/file/YWU3PMsnqZaqr1gABgAFJK/UI-Refresh?node-id=8398-44078

### Rewards navigation component

- [x] Remove the sUSD wallet balance component in the navigation
- [x] Instead, add the Rewards component (see design)
- [x] On component, show:
    - [x] Kwenta icon + OP icon
    - [x] Total value of claimable rewards (OP+Kwenta) in sUSD
- [x] Add dropdown with three rows, showing claimable trading rewards Kwenta, claimable Kwenta $OP rewards as well as claimable $SNX rewards and data according to design
- [x] Network Switcher: Show only network icon and remove name of network in the visible navigation component (see figma design)
- [x] Move network switcher behind wallet address (see design)

### Rewards page

- [x] Add a new Rewards page to (left side) sidebar on Dashboard page
- [x] Remove link to Earn page from left sidebar
    - [x] Add a link button to the Earn page (`/dashboard/earn`) to the left of the 'Staking Docs' button on the Staking page
- [x] Add three "boxes" for each reward type according to design

### Todo

- [x] Hook up trading rewards scripts once ready
- [ ] Update Lore Ipsum texts (ping devDAO PM)
- tbd
