### ISSUE TITLE
Mobile Refresh: High level task list (Design)

### ISSUE THREAD

**Issue by avclarke** [Kwenta/kwenta#2342]
### Global changes

- [ ] Convert all modals to drawers

### Navigation

- [ ] Have all menu items expanded with their sub items split into two columns
- [ ] Update the link color (too dark currently)
- [ ] Add some transitions
- [ ] Fix the up arrow (dev task)
- [ ] Move light / dark toggle out of drop down
- [ ] Add system status and version hash

### Market Page

- [ ] Move margin info bar to the top
- [ ] Slim down margin info and market selector
- [ ] Make the position data more compact (2 columns and could combine margin and leverage)
- [ ] Possibly make the position container separation more obvious (might not be needed once the above is addressed)
- [ ] Separate TP / SL as the combined value can be too long currently

### Trade Panel

- [ ] Anchor long / short to the top of the drawer
- [ ] Add a close button

### Leaderboard

- Anchor the top components
- Redesign the toggle

**Comment by platschi** [comment]
Designs: https://www.figma.com/file/YWU3PMsnqZaqr1gABgAFJK/UI-Refresh?type=design&node-id=8398-48378

**Comment by platschi** [comment]
border bottom missing

![Image](https://github.com/Kwenta/kwenta/assets/548702/3bfb1f02-8a49-4284-83ad-3da07d0c16c4)

**Comment by platschi** [comment]
**animation spec**

hamburger menu:
— slide in/out from left
— dark/light toggle should animate left/right

slide up/down from bottom:
— trade panel 
— get sUSD panel
— close position
— tp/sl edit
— market margin edit
— withdraw margin
— withdraw keeper eth

'available margin' drop down:
— slide down/up on click

any panel that was previous a modal should slide in/out from the bottom
