### ISSUE TITLE
Staking V2 Implementation Checklist

### ISSUE THREAD

**Issue by platschi** [Kwenta/kwenta#2393]
# Ticket Work in Progress

This issue will serve as an overview for tickets and todos with regard to Staking V2.

- [See here for reference document](https://github.com/tommyrharper/shared-notes/blob/main/stakingv2/overview/stakingv2-overview.md)
- [See here for the new smart contracts](https://github.com/Kwenta/token/pull/213)

## Todo
- [x] @tommyrharper: Set up [reference documentation](https://github.com/tommyrharper/shared-notes/blob/main/stakingv2/overview/stakingv2-overview.md)
- [x] @tommyrharper  set up v2 on testnet
- [x] @avclarke: Create first wireframes and user flows with regard to migration, new functionality etc.

## Testnet addresses

You only need to interact with the Proxies, not the implementations.

- RewardEscrowV2 Implementation: 0x0A34aee61770b3cE293Fb17CfC9d4a7F70945260
- RewardEscrowV2 Proxy: 0xf211F298C6985fF4cF6f9488e065292B818163F8
- StakingRewardsV2 Implementation: 0xE0aD43191312D6220DE64aFA54dbdD6982991A87
- StakingRewardsV2 Proxy: 0x3e5371D909Bf1996c95e9D179b0Bc91C26fb1279

## Staking

- Claimable Rewards: Display Claimable Rewards on V1+V2, claim should happen on V2

### Migration flow
- Users will still have tokens on V1, so for min. ~1y need to show both 
- Encourage users to unstake escrow on V1 and restake escrowed Kwenta on V2

// Note: Verify if this applies only to staked Kwenta, or also to escrowed Kwenta (which can't be moved to v2?)
// Note from Tom on the above ^ -> escrowed kwenta can only be moved to V2 after vesting, but users should still have the ability to stake their v1 escrowed kwenta so they can claim the associated rewards on V2.

- Encourage users to unstake liquid Kwenta on V1 and restake liquid Kwenta on V2

- Rewards in Escrow can't be migrated
- Rewards will be based on V1 and V2 funds
- Actual claiming will happen on V2

- V2 has view functions for V1

### Error Handling
- Errors have been changed and will be different, we should be aware of those

## New features
- Ability to offer permissions (delegated staking): Get rewards on behalf, stake escrow on behalf
- Staking Cooldown Period (unstake not possible for 2 weeks on total amount of staked Kwenta; even if you stake 1 Kwenta on top of 1000; cooldown is reset every time n tokens are staked)
- Escrowed entries are transferrable (NFTs): First step unstake escrowed Kwenta, then allow users to transfer escrowed Kwenta to other wallet
- Also possible to bulk transfer escrowed entry NFTs in a single transaction.
- We can fetch historical data now, so that can be utilized for a graph, rewards etc.
