### ISSUE TITLE
SDK Checklist and Notes

### ISSUE THREAD

**Issue by koredefashokun** [Kwenta/kwenta#2651]
The following tasks are expected to be completed before the SDK can be considered feature-complete. This list will likely grow as new features are added.

## General

- [ ] Ensure type correctness of all SDK methods.
- [ ] Set up foundation for retries on select methods.
- [ ] Set up service for interacting with our subgraphs.
- [ ] Remove Duplicated types and move most data types to sdk.
- [ ] Cache contract data where possible, especially settings, config etc which doesn't change very often
- [ ] Create a contracts class in sdk context where we can cache more dynamic contracts such as markets
- [ ] Ensure types are added to all redux actions and reducers
- [ ] Ensure all data is correctly refetched after some mutation e.g. polling for contract and subgraph changes after a transaction
- [ ] Consider experimenting with WebSockets for realtime data (again).
- [ ] Add query statuses for all key queries and create derived query statuses for components which rely on completion of multiple queries
- [ ] Make all sdk number params consistent, e.g. use Wei everywhere instead of BigNumber or string
- [ ] Remove Duplicated types.
- [ ] Create a standard way of passing in numeric values (particularly amounts) to the SDK. Weigh pros and cons of (`Wei`, `ethers.BigNumber` and `string`).

## Exchange

- [ ] Refactor `handleExchange` method.
- [ ] Rename quote/base to from/to.
- [ ] Update the write transactions to use the typed calls
- [ ] Ensure all methods use from/to in correct order.
- [ ] Experiment with exchange contexts (store an instance of from/to pairings, so that the client doesn't have to pass it every time).
- [ ] Reduce number of queries, by storing more data in class instance.
- [ ] Write tests for simple functions.
- [ ] Consider making the provision of the `txProvider` the client's responsibility. It is a little cumbersome to have to call `this.getTxProvider` in nearly every method.
- [ ] Consider ditching currency keys for simple token addresses. The client can choose to load a token list for UI purposes, but the SDK should not be concerned with such details. For balances, we can fetch them as needed.

## Futures

- [ ] Separate methods for isolated and cross-margin accounts.
- [ ] Implement methods for fetching orders, past trades and transfers from the subgraph.
- [ ] Query cross margin accounts from sdk and cache them there.

## Kwenta Token

- [ ] Consider breaking up `getEarnDetails` and `getStakingData` functions.

# Design Considerations

## General

- It is important to understand that checking if certain context properties are initialized cannot be done directly by checking if the property is undefined. This is because the getter throws an error on attempting to access these values when they are undefined.

## Futures

# Notes

- The `ExchangeService` class is still structured very similarly to the `useExchange` hook. It is important to change this, as they are two different paradigms. Without doing this, it is impossible to be efficient with requests and eliminate the overdependence of certain methods on others.
