### ISSUE TITLE
Trade Panel Enhancements

### ISSUE THREAD

**Issue by platschi** [Kwenta/kwenta#2797]
Kwenta allows traders to apply custom "take profit" (TP) and "stop loss" (SL) conditions to their active and prospective positions. 

#### There are two ways to access this feature:
1. During the process of opening/closing a position using the order entry panel.
2. Via a dedicated module when there's an active position.

For visual reference, please view the [screenshot](https://github.com/Kwenta/kwenta/assets/90076964/ae6ffebc-2410-4957-86e9-5431e10c1742).

## Task 1

**Objective:** Provide traders with an exact dollar value representation of their potential profit or loss, in addition to the current percentage display.

**Currently:** When setting a take profit or stop loss, a percentage amount is displayed for the amount either gained or lost (gained on a limit exit, lost on a stop loss exit). This leaves information to be desired.

### Deliverables
- [ ] Integrate a change that shows the dollar amount corresponding to the percentage of profit or loss.
> For instance, a 5% loss could reflect as -$1,200 (representing 5% of the position's value), while a 5% gain would appear as +$2,000 (also 5% of the position's value).

For visual guidance, refer to the provided images:
[Order Entry Panel Reference](https://github.com/Kwenta/kwenta/assets/548702/d5cf67b5-7486-42f1-bde5-5639bb0bed6e)
[TP/SL Model Reference](https://github.com/Kwenta/kwenta/assets/548702/2cde1fde-cda0-45ac-912d-bb4765040579)

## Task 2

**Objective**: Correct the calculation basis for TP/SL percentages when users select prefilled percentages in different states an places within the app.

**Currently:** When users selects one of the prefilled percentage buttons, the value filled into the box is based on the current market price; this can be inaccurate.

### State No 1 - User has an open position 

When an open position exists [(take profit or stops are being set using the pencil icon)](https://github.com/Kwenta/kwenta/assets/90076964/336766fc-8201-4d16-9965-3d59e7c36594), the percentage value and future dollar value (resulting from task 1) are based on the asset's current market price when they should be based on the entry price of the open position.

#### Deliverables
- [ ] Change the TP/SL logic so values are placed based on the position entry price, not the current market price

### State No 2 - User has no open position 

When users selects one of the prefilled percentage buttons [(for a limit or stop order)](https://github.com/Kwenta/kwenta/assets/90076964/a921e58e-c123-4851-aef0-69483adc2a68), the value filled into the box is based on the current market price; which is incorrect. TP/SL orders should be placed against the market price on the market order type, [limit price on the limit order type](https://github.com/Kwenta/kwenta/assets/90076964/669ac2cf-8bc9-4657-852f-a2528a24456b), and [stop price on the stop order type](https://github.com/Kwenta/kwenta/assets/90076964/b7ec7e8c-2ecd-43e3-92c0-90a8ffa14cb0).

#### Deliverables
- [ ] Change the TP/SL percentage button logic for the limit order/stop order tabs to be calculated from user-specified  entry prices, not the current market price

Bounty: 200$ USD paid in $OP
