### ISSUE TITLE
Clean up Kwenta codebase

### ISSUE THREAD

**Issue by platschi** [Kwenta/kwenta#875]
### Subject of the issue
This issue collects notes on code that needs to be cleaned up:

- [x] #1086
- [x] #1073
- [x] #1075
- [x] #1076
- [x] #1077
- [ ] Simplify regression tests
- [ ] #1087
- [x] #1222

### Done
- [x] #1081
- [x] #1082
- [x] #965 
- [x] #930
- [x]  get rid of the `getMarketKey` calls within components and move them inside the queries instead, pending #930 
- [x] #1035
- [x] Increase font size to 13px on Markets page (#966)
- [x] Remove old Shorting code (#1008)
- [x] #1033
- [x] #1079
- [x] #1074
- [x] #1078
- [x] #1080
