### ISSUE TITLE
V1 Deprecation Checklist

### ISSUE THREAD

**Issue by platschi** [Kwenta/kwenta#913]
### Roadmap to deprecate v1

- [x] Fix Subgraph for Spot Synths volumes _(currently waiting for SNX Subgraph to Sync)_ #840
- [x] Merge Synth Tx History into v2 #753 
- [x] Disable non-atomic synths #889 
- [x] Merge Landing Page #865 
- [x] #914

On release day:
- [x] Research implications of renaming branches
- [x] Landing Page: Change Legacy link to `legacy.kwenta.io`
- [x] Update Perp Future Banner Link on `dev` to point to kwenta.io
- [x] Update Secondary Banner to new kwenta page
- [x] Update links on legacy version to point to new kwenta #970
- [x] Merge #967  into main
- [x] Merge v2-dev into v2 #910 
- [x] Github: Rename `main` branch to `v1-main`
- [x] Github: Rename `dev` into `v1-dev`
- [x] Github: Rename `v2-dev` into `dev`
- [x] Github: Rename `v2` into `main`
- [x] Github: Set `dev` as default branch
- [x] Vercel: Make sure kwenta.io now points to a new v2 deploy
- [x] Vercel: Point `v1-main` to `legacy.kwenta.io`
- [x] Deprecate `v2.beta.kwenta.io` (redirect to `kwenta.io`?)
- [x] Deprecate v2 beta hype site
- [x] Update Dhedge on Upgrade
- [x] Update Github Actions to point at correct branches
- [x] Docs: Update Contribution guideline
- [x] devDAO: Inform devs about new branch updates
